---
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Bug Fixing 🐛
      labels:
        - fix
        - bug
    - title: Dependencies changes ⬆️⬇️
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
